services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - env/backend.env
    volumes:
      - ./backend/:/app/backend
      # share svelte output with backend container
      - ./frontend/build:/app/backend/core/static/frontend
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"

  postgres_db:
    container_name: postgres_db
    image: postgres:15.0-alpine
    env_file:
      - env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - env/frontend.env
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "35730:35730"

volumes:
  postgres-data:
  node-modules:
