version: "3.9"

services:
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/:/app/backend
      # share svelte output with backend container
      - ./frontend/public:/app/backend/core/static/frontend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.dev

  postgres_db:
    container_name: postgres_db
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - DOCKER=true
    ports:
      - "35730:35730"

volumes:
  postgres-data:
  node-modules:
